### ISSUE TITLE
How to install webpack-env.d.ts?

### ISSUE THREAD

**Issue by flyon** [Microsoft/types-publisher#135]
See here `webpack-env.d.ts` in DefinitelyTyped: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/webpack/webpack-env.d.ts

But I cannot find `@types/webpack-env` in npm, and installing `@types/webpack` only gives `node_modules/@types/webpack/index.d.ts` which does not contain the contents of `webpack-env.d.ts`. 

So it is possible in another way?

**Comment by mhegazy** [comment]
with https://github.com/Microsoft/types-publisher/pull/136, `webpack-env.d.ts` should be published to `node_modules/@types/webpack/webpack-env.d.ts`

**Comment by mhegazy** [comment]
this has just been merged. so the next time webpack is published it should include the file.

**Comment by flyon** [comment]
Clear, tnx!
