### ISSUE TITLE
@types/ng-table describe an old version of the library - what to do?

### ISSUE THREAD

**Issue by christianacca** [Microsoft/types-publisher#137]
I'm the primary contributor to the [ng-table](https://github.com/esvit/ng-table) project.

I'm rewriting the source code to typescript using es2015 modules. As a consequence the new version of the library will include it's type declarations inside of the main ng-table npm package.

Once this new version of ng-table is published, this will make @types/ng-table only relevant for the old version of ng-table.

Can you advice how to ensure that consumers of the ng-table library will use the correct version of the type declarations?

For example should ng-table be included in https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/notNeededPackages.json

Thanks
Christian

**Comment by mhegazy** [comment]
You need to add your library to the [not-needed](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/notNeededPackages.json) package list. this will publish a new empty @types\ng-table package that does not have any declaration files, but depends on your original package.

Send a PR to DefinitelyTyped types-2.0 branch and I will merge it.

**Comment by christianacca** [comment]
Thanks Mohamed for getting back to me - very useful information. Probably deserves a [blog post](https://blogs.msdn.microsoft.com/typescript/) describing the new work flow for library authors and consumers :-)

Still working on getting the new version to a point I can publish to npm. Once ready I'll make that PR.
