### ISSUE TITLE
npmjs Pages Not Updating Correctly

### ISSUE THREAD

**Issue by tomwanzek** [Microsoft/types-publisher#140]
@RyanCavanaugh thanks for merging the two D3 related PRs yesterday on **DT/types-2.0** !!!

When updating my Angular 2 service for D3, I noticed the following oddity related to the propagation to @types:

* When using `npm install` with **all** `d3-***` module definitions, the correct latest definitions are pulled down from npm with correct version numbers. So the new version parsing works. Thanks @andy-ms :+1: 
* npm search page shows the correct version number for all of them as well in the snippet.

However, for the _only_ following three definitions which were updated yesterday:
* [https://www.npmjs.com/package/@types/d3](https://www.npmjs.com/package/@types/d3)
* [https://www.npmjs.com/package/@types/d3-array](https://www.npmjs.com/package/@types/d3-array)
* [https://www.npmjs.com/package/@types/d3-axis](https://www.npmjs.com/package/@types/d3-axis)

neither the README displayed on npmjs, nor the listed release number are reflective of the npm "latest" package. Again, the npm packages themselves are fine.

**Comment by RyanCavanaugh** [comment]
Somehow we're not doing something right with the NPM API (or their www side is broken). @andy-ms is following up with them to see what's happening

**Comment by tomwanzek** [comment]
Thanks. I know it was odd because most worked just fine. Seeing patterns
where there possibly are none: the modules where it failed are early on in
an alphabetic name sort: d3, d3-array and d3-axis. Maybe it was a timing
thing when the publish jobs hit npm in a certain orders?

**Comment by tomwanzek** [comment]
As an added thought, if you want to check if the error "sort of" reproduces: I created a PR against d3-array earlier today, to change a test file which seems to suffer from a TypeScript@next type inference regression introduced yesterday after the merge. See [DT PR 11205](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11205). I put it in, so DT/types-2.0 tests do not get held up, while I check into the root cause of the changed behavior.

So, you could just merge the PR and see, if it propagates in all respects to npm.

**Comment by tomwanzek** [comment]
@RyanCavanaugh I saw that the PR was merged yesterday on DT. This time it does not seem to have published to npm at all. Did the webhook not run?

**Comment by RyanCavanaugh** [comment]
We have a few pending bugs in the commit -> publish automation that are still being ironed out. @andy-ms can you manually republish?

**Comment by tomwanzek** [comment]
Thx. Could you also republish **d3** and **d3-axis** to see if it takes? The version numbers in particular for **d3** are critical right now. There has been confusion e.g. on angular-cli threads with people thinking @types/d3 already has D3 version 4 definitions.

The fact that these are missing until legacy and new are supported on DefinitelyTyped/types-2.0 is turning out to really complicate matters for consumers. Is there an ETA on that?

**Comment by andy-ms** [comment]
OK, I've force-updated `d3`, `d3-axis`, and `d3-array` and the links on npmjs.com seem to have updated.

**Comment by tomwanzek** [comment]
Thanks. All is well now.

**Comment by RyanCavanaugh** [comment]
We'll be working on the parallel versions structure soon. Not sure on an exact ETA at this time.

**Comment by tomwanzek** [comment]
@RyanCavanaugh thx again.

Over the following days, I will finish the transition from managing the separate repo we used to develop all the D3 v4 definitions to **D2/types-2.0**. In the process, I will probably break out the main Definitions Request issue that tracked everything to date, into more concise, separate issues.

That way this busy team is not necessarily part of issues on DT that are pure content vs thos that require its attention, like the parallel version structure one.

If you have a preference, how to flag/open interrelated issues, I will make it as easy as I possibly can :smile:
