### ISSUE TITLE
Handle dependency pointers

### ISSUE THREAD

**Issue by blakeembrey** [Microsoft/types-publisher#15]
Currently, it seems dependencies rely on some path trickery. This is a pain, because if a definition is ever moved inline you can not deprecate it. Typings resolves this by allowing type definition resolution over multiple sources, but DefinitelyTyped does not prescribe dependencies.

You might want to standardise on using `package.json` internally with DefinitelyTyped to specify dependencies.

**Comment by andy-ms** [comment]
I believe this is resolved by #83.
