### ISSUE TITLE
Update npm packages on DT update? 

### ISSUE THREAD

**Issue by georgeedwards** [Microsoft/types-publisher#151]
I pushed a change with a [PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11610) to the Definitely Typed repo yesterday, which was merged, yet the corresponding [@types/node-schedule](https://www.npmjs.com/package/@types/node-schedule) package on npm hasn't updated to reflect that. 

Is that an expected behaviour, or am I supposed to do something else?

**Comment by mhegazy** [comment]
The automatic publishing happens only on `types-2.0` branch. We manually merge `master` into `types-2.0` once a week or so. At some point in the future we will switch `master` to be a TypeScript 2.0 branch (currently it uses TypeScript 1.8), but we are giving the community some time to migrate to 2.0 first. Once that happens the automatic publishing will work on master as well.

**Comment by mhegazy** [comment]
If you want this package to show up faster, you can submit a merge PR for this package from master into types-2.0.
