### ISSUE TITLE
PRs not being merged to DefinitelyTyped/types-2.0

### ISSUE THREAD

**Issue by tomwanzek** [Microsoft/types-publisher#152]
@RyanCavanaugh @andy-ms I know you mentioned you were doing some dev work on types-publisher and the DT-to-NPM pipeline. Have you put merge/pub fortypes-2.0 on hold for the time being?

If so, could you kindly provide expected timelines when merges resume? Otherwise, there are several simple, yet important PRs which could readily be merged, they have aged for a week now, without any comment or action.

Would appreciate, if they could be moved through. The DT PR numbers are listed below:
* 11497 
* 11503 
* 11542 
* 11573 

Thanks in advance for your attention to the matter.

**Comment by andy-ms** [comment]
Sorry for the delay. I've merged these.

**Comment by tomwanzek** [comment]
Thanks. No worries. I know you are all busy working away on the tooling!!!
