### ISSUE TITLE
Package from DefinitelyTyped not updated at npm

### ISSUE THREAD

**Issue by stephtr** [Microsoft/types-publisher#159]
Sorry for this additional issue. I have looked into several places, but according to these changes in DefinitelyTyped:types-2.0 should automatically trigger an update of the according npm package.
However [DefinitelyTyped #11684](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11684) (change in webpack and new package webpack-env, two days ago) is not online yet.
Is there any action needed?

**Comment by mhegazy** [comment]
@andy-ms can you take a look?

**Comment by andy-ms** [comment]
This was getting plugged up by some other bad commits. The flow should resume when DefinitelyTyped/DefinitelyTyped#11743 and DefinitelyTyped/DefinitelyTyped#11742 merge.

**Comment by stephtr** [comment]
Thank you for the information!
