### ISSUE TITLE
have 'repository' metadata included with npm modules

### ISSUE THREAD

**Issue by joost-de-vries** [Microsoft/types-publisher#16]
I'm looking forward to using the npm way of getting type definitions. Unfortunately the npms are missing the `repository` metadata.
Unfortunately the build infrastructure that I use requires npms to contain this standard metadata.

So my request is for the `repository` metadata to be available in @types npms.

**Comment by RyanCavanaugh** [comment]
:+1: what should this data look like?

**Comment by joost-de-vries** [comment]
If I go to the `package.json` of Typescript itself it has a property 
```
  "repository": {
    "type": "git",
    "url": "git+https://github.com/Microsoft/TypeScript.git"
  }
```
Similarly here the `repository` property would point to the repo where the types source code can be found.

**Comment by joost-de-vries** [comment]
Tx!
