### ISSUE TITLE
When do updates from DefinitelyTyped get pushed to npm?

### ISSUE THREAD

**Issue by eamodio** [Microsoft/types-publisher#164]
I have seen a few packages (`@types/quill`) that have been updated recently on DT but npm is over 3 weeks old.

**Comment by mhegazy** [comment]
`@types` are published from https://github.com/DefinitelyTyped/DefinitelyTyped/tree/types-2.0 branch and not master. They are published every time there is an edit to the package, looking at https://github.com/DefinitelyTyped/DefinitelyTyped/tree/types-2.0/quill, it has not been updated in 28 days, so seems right that you do not see a new version.

We do a manual merge from master to types-2.0 every week or so. if you want to get these changes faster, consider cherry-picking the changes for quill in master, and sending a PR with that to types-2.0 branch.

**Comment by phreed** [comment]
Could you provide the @types/<project> sync schedule in a more obvious place?
Maybe your project wiki.

Could you make recommend a process to make a change to a .d.ts project?
Maybe here...
http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by phreed** [comment]
Three days ago I had a successful PR into 'master'. I see that, in order to get '@types/n3' working I need to make a PR into 'types-2.0'. When TravisCI runs against my clone of 'types-2.0'  it has numerous errors.
The process seems to be broken.

**Comment by mhegazy** [comment]
@phreed, looking into the CI server failures.

**Comment by eamodio** [comment]
@mhegazy so does that mean I should **just** submit PRs to `types-2.0` then? Or does it have to be to both?

**Comment by zhengbli** [comment]
FYI The CI broke because of an recent change in TypeScript@next (some DOM elements are missing by default, like `document` or `console`). Using the TS several days ago works fine.

**Comment by mhegazy** [comment]
> @mhegazy so does that mean I should just submit PRs to types-2.0 then? Or does it have to be to both?

First let me note that this is a transitional period. We are waiting for a few more weeks before making master a TS 2.0 branch, but wanted to give users some time to adopt the release.

As for PRs, if all you care about is `@types` package, then send your PR to types-2.0 for now. if you care about having it in typings/tsd then send it to master, and we will merge it in a week or so. if you want it in both immediately, then send PR to master, then send a merge PR for your change to types-2.0.

**Comment by ibratoev** [comment]
@mhegazy, please share this information publicly. I searched for it in the following places:
* The Readme in the DefinetelyTyped project
* http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html 
* http://definitelytyped.org/guides/contributing.html

The plan to switch DefinetelyTyped *master* to *types-2.0* sounds great. But share that plans somewhere more visible as well. Adding a roadmap and linking to it would be great!

**Comment by andy-ms** [comment]
This is now answered in the README: #12070

**Comment by danielcompton** [comment]
The schedule has changed a little bit since this PR, now it is:

> **My PR is merged; when will the @types NPM package be updated?**
> 
> NPM packages should update within a few hours. If it's been more than 24 hours, ping `@RyanCavanaugh` and `@andy-ms` on the PR to investigate. [README]
> (https://github.com/DefinitelyTyped/DefinitelyTyped#my-pr-is-merged-when-will-the-types-npm-package-be-updated)
