### ISSUE TITLE
Error 404 Not found for type installation

### ISSUE THREAD

**Issue by lihaibh** [Microsoft/types-publisher#167]
I dont know if it is an issue only with particular type declaration i wish to install for my project.
When trying to install the types via the command:

```
npm i @types/fbsdk --save-dev
```

Im receiving an error: 404 Not found : @types/fbsdk even that fbsdk is a valid and found here: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/fbsdk

**Comment by mhegazy** [comment]
Please see https://github.com/Microsoft/types-publisher/issues/151#issuecomment-250812650

**Comment by zhengbli** [comment]
FYI it is renamed to "fb" in the types-2.0 branch. You can try 
`npm i @types/fb --save-dev`
