### ISSUE TITLE
@types/<package> not same as on DefinitelyTyped

### ISSUE THREAD

**Issue by mikekidder** [Microsoft/types-publisher#17]
Doing some initial testing with **react** and related packages; for example _react-router_:

**npm i @types/react-router** -- currently downloads from "tarball": "https://registry.npmjs.org/@types/react/-/react-0.14.21-alpha.tgz"

The index.d.ts file in the tgz -> tar package is not same as found in:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/react-router/react-router.d.ts

even when taking last update of May 25 into consideration.

**Comment by RyanCavanaugh** [comment]
This is correct behavior for now; we have a separate branch for types-compatible definition files that will be eventually merged back into DefinitelyTyped master.

**Comment by RyanCavanaugh** [comment]
This should be the same, either we need to do a republish (this will eventually be automated) or push the branch to the DT repo

**Comment by andy-ms** [comment]
@RyanCavanaugh is this fixed? I can currently install `@types/react-router` and I get a tarball from "https://registry.npmjs.org/@types/react-router/-/react-router-2.0.29.tgz" whose `index.d.ts` is the same as the one in DefinitelyTyped.

**Comment by mikekidder** [comment]
@andy-ms it appears so.  I was able to install: ` @types/react-router `  as well.
Matches those in the **types-2.0** branch on DT repos.  The inter-dependencies look intact, as well as, pulling subfolders w/type definitions 

` @types/react-router ` also wasnt including the lib subfolder previously.  It is now!  

The master branch(s) on DT still seem to be maintained separately, and in the case of - react, react-dom, react-router been recently updated.  The definition files are quite different.  Are their plans to merge?

**Comment by mhegazy** [comment]
>  The definition files are quite different. Are their plans to merge?

we are working out some of the tooling to do the automatic publishing. hopefully it would be operational by next week. We are also working on more frequent merges from master. the issue is the structure of the files have changed, so the merges are not that simple.

**Comment by mikekidder** [comment]
Keep up the great work!  Will close this issue.
