### ISSUE TITLE
c3 out of date

### ISSUE THREAD

**Issue by Lightheaded** [Microsoft/types-publisher#172]
I'm trying to use **@types/c3** in my Angular2 project, but the version that is installed is terribly out of date. [DefinitelyTyped includes the most recent version](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/c3), which exports the module, without which though it's not usable. 

I would be very thankful if you updated it at your earliest convenience.

**Comment by andy-ms** [comment]
The latest `@types/c3`, which is up-to-date with `c3` on the DefinitelyTyped `types-2.0` branch, includes the line `export = c3;`, so it should be importable.
