### ISSUE TITLE
react-native out of date

### ISSUE THREAD

**Issue by dannycochran** [Microsoft/types-publisher#174]
Not sure if this the proper place to request an update for a published package, but @types/react-native (0.29) is behind what's on DefinitelyTyped (0.34):

https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/react-native

**Comment by andy-ms** [comment]
Thanks for the info. Publishing was blocked and a PR is out to fix it: DefinitelyTyped/DefinitelyTyped#12277
