### ISSUE TITLE
Typings with typescript 2.2 not working UNMET PEER DEPENDENCY

### ISSUE THREAD

**Issue by cdekok** [Microsoft/types-publisher#186]
➜  cms-ts git:(master) ✗ npm install @types/body-parser --save-dev
cms-ts@1.0.0 /home/chris/www/cms-ts
├── @types/body-parser@0.0.33 
└── UNMET PEER DEPENDENCY typescript@2.2.0-dev.20161112 extraneous

npm WARN gulp-typescript@3.1.2 requires a peer of typescript@~2.0.3 || >=2.0.0-dev || >=2.1.0-dev but none was installed.
npm WARN cms-ts@1.0.0 No description
npm WARN cms-ts@1.0.0 No repository field.

**Comment by blakeembrey** [comment]
@cdekok Please see the warning:

> npm WARN gulp-typescript@3.1.2 requires a peer of typescript@~2.0.3 || >=2.0.0-dev || >=2.1.0-dev but none was installed.

It's a warning from `gulp-typescript`.

**Comment by cdekok** [comment]
Oops you are correct will report it there
