### ISSUE TITLE
@types/moment-range is out of sync with DT

### ISSUE THREAD

**Issue by magny** [Microsoft/types-publisher#196]
If you look at https://www.npmjs.com/package/@types/moment-range it is version 2.0.3 but the link to https://github.com/DefinitelyTyped/DefinitelyTyped/tree/types-2.0/moment-range at the same page shows that latest version is 2.0.4. If I understand correctly, this new version must’ve been published already. How can I use new definition or is there any way to force publishing newer version to npm?

**Comment by MichalPodeszwa** [comment]
The same problem occurs for Auth0 typings. I also added humanname typings to dt repo, and it still is not seen on npm.

**Comment by andy-ms** [comment]
`npm install @types/moment-range` is now up-to-date with DefinitelyTyped.
I assume @MichalPodeszwa is talking about DefinitelyTyped/DefinitelyTyped#12641, which is also published as `@types/humanparser`.

**Comment by MichalPodeszwa** [comment]
Yes. I did mean humanparser. I mixed those names (several times, actually...) Auth0 is up to date as well. Thank you
