### ISSUE TITLE
Support "not needed" entries

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/types-publisher#2]
We should have the ability to say that a library bundles its own .d.ts file. This would generate a package that just depends on the underlying NPM package, and also generates an entry in the search index so we can surface at TypeSearch.

**Comment by blakeembrey** [comment]
I thought we wanted to avoid this practice because it would fragment the ecosystem. I think it's clearer to publish a dummy version and immediately deprecate it so NPM will warn on installation (assuming you want this at all). The dummy version could even error on runtime.

**Comment by andy-ms** [comment]
Resolved by #23
