### ISSUE TITLE
New package inert not published to npm @types

### ISSUE THREAD

**Issue by nycdotnet** [Microsoft/types-publisher#227]
Greetings,

I submitted a PR to definitely typed yesterday for the `inert` package to the types 2.0 branch and after CI passed, I merged it in.  https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13310

I noticed that it's not yet up on npm.  Do I need to be on a list or something to have PRs I merge get uploaded to @types or is there perhaps a CLA I need to sign?

Thanks

**Comment by andy-ms** [comment]
It's up (`npm info @types/alert`). We recently transitioned from `types-2.0` to `master` so your package was probably not published immediately.

**Comment by nycdotnet** [comment]
Thanks - sorry to bug you.
