### ISSUE TITLE
Generated types directives need to be lower case

### ISSUE THREAD

**Issue by weswigham** [Microsoft/types-publisher#24]
Otherwise resolution will fail on case-sensitive filesystems, as NPM enforces lower-cased package names.

This issue is exhibited in orchetrator's index, which contains the line:
```ts
/// <reference types="Q" />
```

and it must be
```ts
/// <reference types="q" />
```

**Comment by andy-ms** [comment]
`output/orchestrator/index.d.ts` is copied from DefinitelyTyped, not generated.
We could add something to  https://github.com/DefinitelyTyped/definition-tester. Something like:

    const src = ts.createSourceFile(fileName, readFile(fileName), ts.ScriptTarget.Latest, true);
    for (const ref of src.typeReferenceDirectives) {
        if (/[A-Z]/.test(ref.fileName)) {
            throw new Error(`${filename}'s reference to ${ref.fileName} should be lower-cased.`);
        }
    };

**Comment by RyanCavanaugh** [comment]
@andy-ms can you talk to Raghav about adding that? He's doing some definition-tester changes right now

**Comment by andy-ms** [comment]
@rakatyal

**Comment by rakatyal** [comment]
Fixed [here](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/395c4e163906c089dd23ec7180a7d167b4d097b0).
