### ISSUE TITLE
NPM Pages for D3 module defintions missing/incorrect Data

### ISSUE THREAD

**Issue by tomwanzek** [Microsoft/types-publisher#285]
@andy-ms I just noticed that the npm @types pages for the **d3** and **d3-####*** modules do not reflect the latest releases and/or are missing their README info.

`npm view` shows the correct info and the npm search page summary displays the correct release info.

Not sure, when this would have happened. Thanks for looking into it.

**Comment by tomwanzek** [comment]
Is this being looked into? Thx. T

**Comment by andy-ms** [comment]
Are you still seeing this problem?

**Comment by tomwanzek** [comment]
I just went through the definitions on npm, the following still seem to have issues with the README on npm:

- [ ] d3-axis
- [ ] d3-brush
- [ ] d3-collection
- [ ] d3-color
- [ ] d3-dispatch
- [ ] d3-drag
- [ ] d3-force
- [ ] d3-format
- [ ] d3-geo _[no need to tackle, there is a new [DT PR 14831](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14831)which should be published soon]_
- [ ] d3-hsv
- [ ] d3-interpolate
- [ ] d3-path
- [ ] d3-polygon
- [ ] d3-quadtree
- [ ] d3-queue
- [ ] d3-random
- [ ] d3-request
- [ ] d3-scale-chromatic
- [ ] d3-selection-multi
- [ ] d3-time-format
- [ ] d3-time
- [ ] d3-time-format
- [ ] d3-timer
- [ ] d3-voronoi

I suspect, it happened when the `types-2.0` branch was "merged" into `master` and published? Seems to have been around that time. The remaining d3 module definitions have seen a new release pushed since, so they appear correct on the npm module page.

Thanks for looking into the rest.

**Comment by tomwanzek** [comment]
d3-geo has been fixed due to the latest PR being published.
There is a new PR in the pipeline, which should  update d3-format, once published.

Otherwise, this is still an issue. It would be most appreciated, if this could be fixed without having to wait for an actual change PR due to a change in the underlying module definitions.

**Comment by tomwanzek** [comment]
Updated the checklist above to reflect the packages where the README still does not appear on the npm package  page.

**Comment by tomwanzek** [comment]
@andy-ms I just scanned the above checklist again on `npm/@types`. There are still 16 modules for which the npm splash page is not displayed correctly (i.p. no README.)

Is there a quick way to just re-publish the existing packages so the README sticks? It's been 4 months and the only ones that have dropped from the list are those that have seen merges to DT since the migration from `types-2.0` to `types` proper.

Thanks a lot in advance. T

**Comment by andy-ms** [comment]
Types-publisher needs a new commit hash to publish a new version. You could lint the non-updated packages.

**Comment by tomwanzek** [comment]
Thanks, will see what I can do to trigger it. Cheers, T

**Comment by tomwanzek** [comment]
I have submitted DefinitelyTyped/DefinitelyTyped#16536 which touches all affected modules. Unfortunately, it has a prerequisite linting fix in **d3-shape**, which is part of DefinitelyTyped/DefinitelyTyped#16508.

**Comment by tomwanzek** [comment]
@andy-ms Thanks, except for `d3-path` all is up-to-date now and complete again. I will push something no-op-like to `d3-path` to force a  content hash change to its `index.d.ts`. The linting changes to the test file and `tslint.json` obviously were not enough. But for all intents and purposes, this issue is addressed. Cheers, T
