### ISSUE TITLE
Subdirectory under package directory for previous version are not published

### ISSUE THREAD

**Issue by rokadias** [Microsoft/types-publisher#309]
Following the guidelines in the FAQ for DefinitelyTyped. I added a v7 folder for creating a major version update. However the resulting npm package doesn't contain any subdirectories.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#i-want-to-update-a-package-to-a-new-major-version

Here's the DefinitelyTyped issue and corresponding changes that I tried:
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/14560

Performing `npm install auth0-js` does not have a `node_modules/@types/auth0-js/v7` directory.

**Comment by blakeembrey** [comment]
@rokadias The `auth0-js` release should not contain multiple versions. Instead, there's multiple versions on NPM for that. If you wanted `7.x`, you should install `@types/auth0-js@7.x`. I see these:

```
     '8.0.0-beta.3': '2016-12-19T13:36:21.518Z',
     '7.6.1': '2017-01-03T19:53:28.835Z',
     '8.0.0': '2017-01-03T23:38:11.502Z',
     '8.0.1': '2017-01-04T18:46:13.587Z',
```
