### ISSUE TITLE
Support Node 7

### ISSUE THREAD

**Issue by jribe** [Microsoft/types-publisher#313]
`package.json` has

```
"engines": {
  "node": "^6.9.1"
}
```

Does this project actually have incompatibilities with Node 7 or is it defensive programming? The incompatibility is a minor annoyance for contributing to https://github.com/DefinitelyTyped/DefinitelyTyped, requiring the user to run npm/yarn with `--ignore-engines`.

**Comment by andy-ms** [comment]
Whoops, should have just set a lower bound. Should be fixed by DefinitelyTyped/DefinitelyTyped#14818.
