### ISSUE TITLE
Should allow multiple test files

### ISSUE THREAD

**Issue by tkrotoff** [microsoft/types-publisher#318]
Error [`Expected file ... to be named '...-tests.ts'`](https://github.com/Microsoft/types-publisher/blob/master/src/lib/definition-parser.ts#L158) is too restrictive.

Sometimes you need to have multiple test files.

Edit: see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15170, it's a good use case

**Comment by andy-ms** [comment]
Create a `test` directory.

**Comment by tkrotoff** [comment]
@andy-ms great :)
You could just update the error message with something like `File fooBar.ts should be named 'fooBar-tests.ts' or moved inside a directory named 'test'`
