### ISSUE TITLE
could u add a type definition of gonzale-pe

### ISSUE THREAD

**Issue by Aaronphy** [Microsoft/types-publisher#327]
I am writing a vscode extension and use a npm package called "gonzales-pe"  .

but there is no typescript definition  of this pacakge ? 

could u add one for that ? or  How can I publish a @types/gonzales-pe to npm

**Comment by RyanCavanaugh** [comment]
These types are sourced from https://github.com/DefinitelyTyped/DefinitelyTyped; submit a PR there and it will be published to `@types` automatically

**Comment by Aaronphy** [comment]
@RyanCavanaugh  Is  there  PR`s  standard docs?

**Comment by RyanCavanaugh** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped#how-can-i-contribute
