### ISSUE TITLE
Missing types-metadata.json

### ISSUE THREAD

**Issue by michaelgerakis** [Microsoft/types-publisher#334]
Some packages that have been updated recently are missing type-metadata.json. For example, @types/graphlib and @types/color. I believe this might have to do with the change in directory structure in DefinitelyTyped.

I am not sure if related, but the npm pages for these packages also seem off. For example, https://www.npmjs.com/package/@types/graphlib. On the left it says that the package was published 3 days ago, but the Details section says that the last update was January. Also the link to the exported files in DefinitelyTyped leads to a 403 (because of the lacking types directory in the URL).

**Comment by andy-ms** [comment]
We got rid of this in #306. 
Other issue fixed by #324.
