### ISSUE TITLE
Ignore npm@5 package-lock.json

### ISSUE THREAD

**Issue by mxl** [Microsoft/types-publisher#350]
Currently running `npm test` in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) repo with npm version 5 results in generating `package-lock.json` for definitions having `package.json`, e.g. multer-s3. Because of that `npm test` fails with:

> Error: Directory /../DefinitelyTyped/types/multer-s3 has unused file package-lock.json
>     at /.../DefinitelyTyped/node_modules/types-publisher/src/lib/definition-parser.ts:348:11
>     at Generator.next (<anonymous>)
>     at fulfilled (/.../DefinitelyTyped/node_modules/types-publisher/bin/lib/definition-parser.js:4:58)

**Comment by nik-john** [comment]
I'm having the same issue. Any luck with resolutions?

**Comment by mxl** [comment]
@nik-john I submitted #351 which fixes this issue.
