### ISSUE TITLE
Add inferred dependencies to peerDependencies? 

### ISSUE THREAD

**Issue by sthuck** [Microsoft/types-publisher#366]
Hi guys,

I'll start with the example scenario -
my package.json has these dependencies:
```
    "@types/angular": "~1.5.0",
    "@types/angular-mocks": "^1.5.0"
```
and `@types/angular-mocks` package.json looks like this, as it's dependencies are automatically inferred:
```
 "dependencies": {
        "@types/angular": "*"
    },
```
since `@types/angular": "*"` gets resolved to @types/angular version 1.6.23 (in Yarn 0.27.5), I end up with the types for angular 1.6. Obviously this is just an example and will happen with any type definitions that has breaking changes compared to previous type definitions. 

You can see the discussion with yarn guys https://github.com/yarnpkg/yarn/issues/3951, where they explain why '*' is being resolved to latest version and not simply to "any version". They suggest using `peerDependencies` instead, which does seem (to me at least) like the correct thing to do. 

I do understand this has potential to pop up a 'missing peer dependency' error for lots and lots of people.
But if I understand this bug correctly, as time will pass and new type definitions will break previous versions, more yarn users will experience this issue. So I guess this is for your consideration...

**Comment by cwmoo740** [comment]
Ditto for react.

```
"@types/react": "^15.6.0",
"@types/react-dom": "^15.5.0"
```

where "@types/react-dom" has:

```
"@types/react": "*"
```

This results in the structure:

```
node_modules
-@types
--react (15.6.0)
--react-dom
---node_modules
----@types
-----react (15.0.33)
```

@sthuck and the yarn people seemed to indicate that yarn would pick "latest" for a dependency of *, but that doesn't seem to be the case here.

**Comment by gilamran** [comment]
Installing 
`@types/react@^15.6.1`
`@types/react-dom@^15.5.2` (Depends on `@types/react@*`)

Will install nested `node_modules/@types/react-dom/node_modules/@types/react` (version 16, the latest).

This will cause many errors like this one:
```
node_modules/@types/react-dom/node_modules/@types/react/index.d.ts(3422,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'a' must be of type 'DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>', but here has type 'DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>'.
```

**Comment by cwmoo740** [comment]
There's a few lines in yarn.lock that look something like:

```
"@types/react@*":
  resolved: some_url

"@types/react@15.6.0":
  resolved: some_url
```

manually editing these to combine react@* and react@15.6.0 fixes the problem:

```
"@types/react@*", "@types/react@^15.6.0":
  resolved: some_url
```

this will cause all of the dependencies on `@types/react@*` to resolve the way you expect.
