### ISSUE TITLE
When are types published?

### ISSUE THREAD

**Issue by johnnyreilly** [Microsoft/types-publisher#384]
How long does it take for type definitions to be published? I tweaked https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-icons about 24 hours ago. ([PR here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20191)) 

However it's not showing up on npm yet. 

There doesn't seem to be any way to discover if a definition has failed to be published or something. Is this published once a week perhaps? Some documentation around this would be useful for people wondering where updated type definitions are...

**Comment by johnnyreilly** [comment]
Now it's published which is lovely - would still be great to get more visibility out there around publish times etc for when people have questions.  Thanks!

**Comment by RyanCavanaugh** [comment]
@andy-ms can explain the schedule. I believe it's approximately hourly?

**Comment by johnnyreilly** [comment]
I'd love to know - this one took around 30-odd hours to get published. FWIW it contains around 3000 new definition files (generation was automated!) So it's larger than your average definition update. But I wouldn't have imagined that was a factor...

**Comment by GlenCFL** [comment]
There's definitely something weird going on with the publishing.

I added a new version to [atom](https://www.npmjs.com/package/@types/atom), which resulted in v0 being created. v0 was updated within a few hours, yet the new version wasn't published for about 20 hours. [text-buffer](https://www.npmjs.com/package/@types/text-buffer) had a new version pushed as well, with the latest version still not being available. That actually means that atom is going to give off TypeScript errors if it's installed right now, as it depends on types from that new version of text-buffer.

**Comment by andy-ms** [comment]
A key expired over the weekend. I'm setting up a fresh one now.

**Comment by johnnyreilly** [comment]
Thanks @andy-ms - is there a straightforward way to get some visibility around types publishing?  Perhaps something as simple as adding more information to the tracking issue? https://github.com/Microsoft/types-publisher/issues/40

**Comment by sandersn** [comment]
@johnnyreilly This should be fixed now, with watchdog badges on DefinitelyTyped's README page, and updates to merged PRs when a package publishes.

Also, internally, types-publisher now publishes at least every half-hour, which is different from last year's solely on-demand schedule.
