### ISSUE TITLE
[Request] Typing for React Module

### ISSUE THREAD

**Issue by granticusmaximus** [Microsoft/types-publisher#435]
[This React Module](https://github.com/nickeljew/react-month-picker) is my request to have typings for. I am a new developer, trying to learn how to make the typings for this module, but I am getting stuck and scrapped the `@types` for it.

I would request guidance for this if it is wished that I would need to create it.

**Comment by RyanCavanaugh** [comment]
This isn't an issue tracker for definition help. You might try DefinitelyTyped, which has a lot of documentation and examples to work from.
