### ISSUE TITLE
Definition files in sub folders are not detected

### ISSUE THREAD

**Issue by rhmoller** [Microsoft/types-publisher#45]
When the definition-parser scans for .d.ts files, it should also look in sub-folders.

https://github.com/Microsoft/types-publisher/blob/master/src/lib/definition-parser.ts#L74

This affects react-router and other modules. See Microsoft/Typescript#9488

**Comment by mhegazy** [comment]
this is tracked by https://github.com/Microsoft/types-publisher/issues/3

**Comment by mhegazy** [comment]
I should add that PRs are always welcomed

**Comment by rhmoller** [comment]
It is not entirely the same. #3 is about a structure for maintaining typings for multiple versions of a library.

This issue is about supporting definitions that are split into multiple files with some of the files in a sub-folder

**Comment by mhegazy** [comment]
ah i see.

**Comment by andy-ms** [comment]
Closed by #53
