### ISSUE TITLE
@types/del should depend on @types/glob, but doesn't

### ISSUE THREAD

**Issue by weswigham** [Microsoft/types-publisher#46]
[`del`](https://www.npmjs.com/package/@types/del) imports [`glob`](https://www.npmjs.com/package/@types/glob), but `glob` isn't listed as a dependency in `del`'s `package.json`.

**Comment by mhegazy** [comment]
fixed by `del@2.2.29-alpha` and `@types/glob@5.0.28-alpha` respectively
