### ISSUE TITLE
Should TypeScript@next be removed from the test runner?

### ISSUE THREAD

**Issue by thw0rted** [Microsoft/types-publisher#478]
I don't know if this issue belongs here or in DT, since it's actually about running DT tests, but I think the behavior I'm seeing is implemented by types-publisher.  If this is the wrong place, feel free to close and I'll open a new ticket there.

Anyway, I'm trying to test some small DT updates I made using the same process I did before:

* Check out DT
* Make changes
* `npm run lint node`
* `npm test`

I found a few lint violations and test failures that couldn't be related to changes I made, so I started digging.  2 hours later, it turns out the root cause is that TS@next is a [moving](https://github.com/Microsoft/TSJS-lib-generator/pull/565) [target](https://github.com/Microsoft/TSJS-lib-generator/issues/558) -- they're futzing with the DOM and it's breaking tests on a day-to-day basis.

Obviously, we want to know if breaking changes are coming, so you'd want to retain some way of testing against TS@next, but certainly the Travis build for DT shouldn't flag your PR as bad just because today's TS@next modeled the world differently than it was when you ran the same test against the same code.

**Comment by thw0rted** [comment]
I believe this is the root cause why [my DT PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/28075) was closed without merging.  Maybe cc @andy-ms ?

**Comment by sandersn** [comment]
This is a feature, not a bug. We want Definitely Typed definitions to work with the new version of typescript as soon as it comes out.

I added a nightly run of typescript@next on Definitely Typed to make sure this stays true for existing packages too: https://typescript.visualstudio.com/TypeScript/_build?definitionId=15&_a=summary
