### ISSUE TITLE
Are types being published right now?

### ISSUE THREAD

**Issue by johnnyreilly** [Microsoft/types-publisher#485]
Are types being published right now? My PR was merged yesterday but there's no sign on npm:

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/29186

https://www.npmjs.com/package/@types/recharts

https://www.npmjs.com/package/@types/recharts-scale

More generally, it would be great if we could get some visibility on the types publishing process; at present there's no information available between merging and publishing which can lead the puzzlement! This had been mentioned previously but I'm not aware of any remedies.

Interestingly in the linked issue a key had expired. That was 12 months ago - I can't help but wonder if the same might have happened?

https://github.com/Microsoft/types-publisher/issues/384

**Comment by RyanCavanaugh** [comment]
#40 tracks server status. @andy-ms can you investigate?

**Comment by johnnyreilly** [comment]
Sorry to chase - just wondering if there was any news on this?

**Comment by johnnyreilly** [comment]
Looks like we're back! Thanks!
