### ISSUE TITLE
Wrong typings being published for node

### ISSUE THREAD

**Issue by SimonSchick** [Microsoft/types-publisher#494]
@andy-ms 

Something seems to be broken in the types publisher:

```
➜  sbox npm i @types/node@8

+ @types/node@8.10.32
updated 1 package and audited 1 package in 1.28s
found 0 vulnerabilities

➜  sbox cat node_modules/@types/node/index.d.ts | head -n1
// Type definitions for Node.js 10.11

➜  sbox cat node_modules/@types/node/package.json | jq .version
"8.10.32"
``` 

It seems `@types/node@8` is shipping typings for v10 instead.

Related: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/29380

cc @anthonyvercolano

**Comment by SimonSchick** [comment]
So this seems to be an isolated issue for node 8.10 typings.
I assume the fact that the header in the node v8 typings is technically incorrect as it's suffixed with `.x` which probably throws your parser off, I noticed this earlier when I enabled linting for node v10 typings as the linter warned me about this.

See https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ffa84d3a0e8b4f8cea973d69a062d08d429d2e5a/types/node/v8/index.d.ts#L1

**Comment by andy-ms** [comment]
Looking into this.

**Comment by SimonSchick** [comment]
ty
