### ISSUE TITLE
Please add vue-property-decorator to the whitelist

### ISSUE THREAD

**Issue by janesser** [Microsoft/types-publisher#504]
With https://github.com/DefinitelyTyped/DefinitelyTyped/pull/29931 i am actually shipping vuelidate typescript support, which depends on vue-property-decorator.

Is there some criteria to meet?

@andy-ms do you want me to provide a PR?

**Comment by andy-ms** [comment]
It looks like `vue-property-decorator` is only used in tests in that PR. Would it be possibly to write the tests to *just* test `vuelidate`? Note that tests just need to typecheck, not run, so you could add `declare const` to represent other libraries if necessary.

**Comment by janesser** [comment]
@andy-ms thanks for the quick answer.

point is that vuelidate is nested in the @component annotation, which need to be either imported from vue-class-component or vue-property-decorator, which ships it indirectly.

In my opinion test-case should be close to real usage scenario. For now including vue-property-decorator sounds like the way to get there.

Do i miss some alternative?

**Comment by andy-ms** [comment]
I don't think it's worth it to whitelist a new external dependency (which would get added as a dependency of the `@types` package) just for tests -- it should be possible to write a simple shim for `vue-property-decorator`. It doesn't have to actually work at runtime, just have the right type.

**Comment by janesser** [comment]
Thanks for your advice,
regarding the parts from vue-property-declarator i have been able to create some "shims" that fullfil the job nicely. I noticed that "// $ExpectType CustomRule" will not work with type aliases, well fine.

But there is yet another issue with @types/vue which clearly deprecated, see https://www.npmjs.com/package/@types/vue.

It comes handy to be still availble in the whitelist even, although it feels wrong using deprecated things.

I tried to create shims for this one as well, but the module augmentation does not work with w<hat i tried.

@andy-ms 
You could do me a big favour in pointing me to an example of "module augmentation" working with shims, is there something like that?

Regards

**Comment by andy-ms** [comment]
`@types/vue` was deprecated because `vue` has its own types  now, so you should probably be using that instead.
Not sure what you mean by module augmentation of a shim -- if you're not using a module and using a shim instead you presumably don't need to augment it? Or if that module had included an augmentation of something else, you could just copy that to your tests file.

**Comment by janesser** [comment]
@andy-ms it is about augmentation of "vue/types/vue" with @types/vue as dependency it works fine.

depending on original typing of vue, would probably require another whitelisting, that's why i tried to declare the parts of "vue/types/vue" in the test, but the augmentation from vue.d.ts does not apply.

**Comment by andy-ms** [comment]
`vue` itself is already in the whitelist.
