### ISSUE TITLE
What about the declarations in the "typings" registry and "typed-typings" organization?

### ISSUE THREAD

**Issue by ivanz** [Microsoft/types-publisher#51]
What is the plan (if any) for the [`typings` registry](https://github.com/typings/registry/) and typings already published [as npm packages](https://github.com/typings/registry/tree/master/npm)? Also the [`typed-typings` organization](https://github.com/typed-typings)?

An example is the `chai` typings package where DefinitelyTyped has version 3.4.0, but the `typings` registry has the latest 3.5.0 ( https://github.com/typings/registry/blob/master/npm/chai.json )

**Comment by mhegazy** [comment]
We still need to add support for redirect, to match the typings registry features, this is tracked by https://github.com/Microsoft/types-publisher/issues/4.

As for the this specific library, i would recommend moving the latest to definitelytyped.

**Comment by blakeembrey** [comment]
So, I just realised a clever trick I can start implementing ASAP. I can set the `package.json` names of repos in @types to `@types/<name>`. Then, once you install it, it'll automatically be placed in the location TypeScript needs to look it up. That way everything in @types can be supported until redirects are properly implemented.

**Comment by blakeembrey** [comment]
However, this pattern won't work with the existing approach that uses subdirectories for each version, but it's a good start from the @types org side.
