### ISSUE TITLE
Improve notNeededPackages.json testing

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/types-publisher#515]
Currently we don't do any testing when `notNeededPackages.json` is changed. When a package is added to it we should ensure:
* The directory it was in no longer exists.
* Nothing depends on it.
* The `asOfVersion` is higher than the last published version.

**Comment by sandersn** [comment]
Also check that
1. libraryName matches a real npm name.
2. asOfVersion matches, for major.minor, a real version of the npm package.

When (1) is false, types-publisher crashes currently.
