### ISSUE TITLE
Node.js types are incorrect/outdated

### ISSUE THREAD

**Issue by mike-morrison** [Microsoft/types-publisher#52]
#### Steps to reproduce:

npm install @types/node

#### Expected Results: 

The node v6 typings should be in index.d.ts in the node_modules/@types/node directory.

#### Actual Results:

The node v4 typings are in index.d.ts in the node_modules/@types/node directory.

**Comment by mhegazy** [comment]
The definition file is what is on definitelytyped (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/node/index.d.ts). Please send DefinitelyTyped a PR for the updated definitions, and i will get it published to `@types`

**Comment by mike-morrison** [comment]
[Master Branch](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/node/node.d.ts)

I guess typings installs from the master branch by default?

**Comment by mhegazy** [comment]
We should be doing a merge from master in the next few days.

**Comment by mhegazy** [comment]
@rakatyal can we get a merge done this week?

**Comment by felixfbecker** [comment]
Why are the typings not built from https://github.com/types/env-node?

**Comment by mhegazy** [comment]
The packages are published from definitlytyped, if you believe this is more accurate feel free to update the one in definitlytyped to match it.

**Comment by blakeembrey** [comment]
@mhegazy Can we try to prioritise redirects so duplicated efforts can be reduced ASAP? @types can even support NPM installs directly using git but a lot of people find it difficult to contribute to DefinitelyTyped (especially if they'd want to help maintain a definition instead of contributing it once and forgetting about it).

**Comment by mhegazy** [comment]
For context, redirects is tracked by https://github.com/Microsoft/types-publisher/issues/4

We would be happy to take PRs for this feature if anyone is interested in contributing. most of the infrastructure is already in place.

**Comment by andy-ms** [comment]
Looks like this can be closed now as `@types/node` now has 6.0 typings and we have a separate issue for redirects.
