### ISSUE TITLE
Angular @types package references itself

### ISSUE THREAD

**Issue by joeskeen** [Microsoft/types-publisher#57]
I was trying to get an Angular 1.x project working with TypeScript 2.0 using the `@types/angular` typings.  I kept on getting duplicate identifier errors in the .d.ts files, even when using the new `skipLibCheck` option.  What I finally discovered as I dug into it is that when you install the Angular types, you get a nested structure looking like this: `node_modules/@types/angular/node_modules/@types/angular`
Deleting the `node_modules` folder under `node_modules/@types/angular` resolved the errors.
Upon further inspection, I realized that the `package.json` file created for the Angular typings had a package id of `@types/angular@1.5.5-alpha` and a dependency on `"@types/angular": "1.5.4-alpha"`.
You can also see the dependency on the NPM page for the Angular typings: https://www.npmjs.com/package/@types/angular
Is there any way to prevent this from happening?

**Comment by andy-ms** [comment]
Fixed by #63
