### ISSUE TITLE
Warn for unused files in DefinitelyTyped directories

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/types-publisher#68]
The only values included in a directory in DefinitelyTyped should be an entry point `.d.ts` (usu. `index.d.ts`), other `.d.ts` files referenced by that, and (optionally) test files and a partial `package.json`.
Currently we also store old versions of a definition in the same directory; we should move these to their own directory instead (or just throw them out).

For example, every `.d.ts` file in `bingmaps` except for the index is currently ignored.

**Comment by alexeagle** [comment]
How do you know those files are unused? eg. `BusinessDetails` doesn't appear in `bingmaps/index.d.ts` nor is the `Microsoft.Maps.Directions.d.ts` file referenced there.

**Comment by mhegazy** [comment]
I believe @andy-ms means published by the types-published by "used ". so we should warn the package author that these files will never make it to the corresponding `@types` package. they have two options, either put them in the `tsconfig.json`, or add a `/// <reference path.. ./>` to them.

**Comment by mhegazy** [comment]
@andy-ms how would you handle cases like older versions of the library?

**Comment by andy-ms** [comment]
We would have to add functionality to handle multiple versions first.

**Comment by felixfbecker** [comment]
What about typings for https://github.com/normalize/mz? There is no main entry point, but an fs.js, child_process.js etc. that are importet with `import * as fs from 'mz/fs'`.

**Comment by andy-ms** [comment]
The files are listed in the [tsconfig.json](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/mz/tsconfig.json), so they get published.

**Comment by andy-ms** [comment]
Fixed by #264

**Comment by pmoleri** [comment]
Hi, DT types-2.0 branch seems to be failing due to this check:

First I get this error:
```
# Typing Publish Report Summary
Started at Tue, 17 Jan 2017 15:10:11 GMT
Found 2719 typings folders in C:\Work\repos\DefinitelyTyped
Error: In C:\Work\repos\DefinitelyTyped/ace: Expected file 'all-tests.ts' to be named ace-tests.ts
    at C:\Work\repos\DefinitelyTyped\node_modules\types-publisher\src\lib\definition-parser.ts:155:12
    at next (native)
    at fulfilled (C:\Work\repos\DefinitelyTyped\node_modules\types-publisher\bin\lib\definition-parser.js:4:58)
```

After that is fixed, I get this other error even after referencing the file in `ace-tests`:
```
# Typing Publish Report Summary
Started at Tue, 17 Jan 2017 15:13:33 GMT
Found 2719 typings folders in C:\Work\repos\DefinitelyTyped
Error: Directory C:\Work\repos\DefinitelyTyped/ace/tests has unused file ace-anchor-tests.ts
    at C:\Work\repos\DefinitelyTyped\node_modules\types-publisher\src\lib\definition-parser.ts:311:11
    at next (native)
    at fulfilled (C:\Work\repos\DefinitelyTyped\node_modules\types-publisher\bin\lib\definition-parser.js:4:58)
```

To reproduce a clean `npm install` is needed so the last `types-publisher` version is installed.

**Comment by andy-ms** [comment]
See DefinitelyTyped/DefinitelyTyped#13233

**Comment by pmoleri** [comment]
Great. I just saw the comment on my PR to types-2.0.
