### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by reach4thelasers** [Microsoft/types-publisher#73]
The README for this project launches into detail with no explanation of what this project is for.  I'm using another GitHub lib which is using this, and it seems broken, but I have no idea what this library's purpose is.  

Could you add some context information to the ReadMe please?

**Comment by RyanCavanaugh** [comment]
Who's using this?

**Comment by jeffijoe** [comment]
I'd like to know how to use this as well.

**Comment by RyanCavanaugh** [comment]
This script takes definitions from DefinitelyTyped, does some parsing work to extract metadata, and publishes them to the `types` account on NPM. In theory there's nothing useful here for anyone but the owner of that NPM account.

If there's functionality from the project you'd like to use, I'd *strongly* recommend filing an issue detailing that. The script isn't intended for public consumption (i.e. we will break the API whenever convenient for us) but we intend to refactor some common parts into a separate library that can be used by both this project and the DefinitelyTyped test runner, so if we know which parts people would like to consume externally, we can move those into that library.
