### ISSUE TITLE
No verification on dependencies

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/types-publisher#8]
There's nothing stopping a user from publishing a thing that imports a package even if said package wasn't listed as a dependency in `package.json`

**Comment by blakeembrey** [comment]
@DanielRosenwasser Can you elaborate on this? Is this about dependencies on published typings having to mirror the official NPM dependencies?

**Comment by DanielRosenwasser** [comment]
No, I think this came up when I needed to use the Ember `.d.ts`, but its dependency on JQuery wasn't automatically satisfied. I was confused over the fact that `@types/ember` was even allowed to be published without an explicit dependency on `@types/jquery`.

I think @RyanCavanaugh fixed this anyway though.
