### ISSUE TITLE
@types/react-redux on npm is outdated, on DT there are fixes already

### ISSUE THREAD

**Issue by brunolm** [Microsoft/types-publisher#96]
I'm having an issue with [@types/react-redux](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/react-redux/index.d.ts) I saw that there was a fix 3 days ago https://github.com/DefinitelyTyped/DefinitelyTyped/commit/b488f3cb5f70ea62c66a3ecaef4e38baadf3727c

But on NPM the latest published was 2 weeks ago.

What can I do?

**Comment by RyanCavanaugh** [comment]
We're working a merge and will be publishing an updated set of packages (along with starting automatic rolling publishes) in the next few days

**Comment by RyanCavanaugh** [comment]
Manual publish happened this morning. Andy's figuring out what happened to the READMEs.

**Comment by MeirionHughes** [comment]
@RyanCavanaugh So are updates still done manually or are they automatic? Are they a nightly thing or trigger on webhook?

**Comment by mhegazy** [comment]
It is a webhook now. so merging something to types-2.0 triggers a publish to npm.

**Comment by MeirionHughes** [comment]
@mhegazy is that something I need to do myself (PR master -> types-2.0)?

**Comment by MeirionHughes** [comment]
@mhegazy changes I made (parse5) that have been merged into `types-2.0` don't seem to have made it to [npm ](https://www.npmjs.com/package/@types/parse5). :/

**Comment by RyanCavanaugh** [comment]
@andy-ms is the hook running in full live mode?

**Comment by andy-ms** [comment]
Azure started showing that `'git' is not recognized as an internal or external command`. #117 should fix this.
The remaining uses of `child_process` are in `unpublish` (which will not run on the server) and `validate` (see #120).

**Comment by andy-ms** [comment]
Fixed by https://github.com/Microsoft/types-publisher/commit/7fb71b9400c5db8f69430a7a22a2809b202e8c1b

**Comment by aleung** [comment]
@mhegazy @RyanCavanaugh 
Shall I merge to types-2.0 branch as well when I commit on master brach on DT repo? Or there is a team responsible to merge all changes on master to types-2.0 periodically?

**Comment by aleung** [comment]
I've found the answer in https://github.com/DefinitelyTyped/DefinitelyTyped/issues/10711#issuecomment-240939318

Hope that there is a clear instruction for contributor.
